# https://taskfile.dev/
version: '3'

vars:
  GO_PACKAGES:
    sh: go list ./...

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: run chop
    cmds:
      - task: build
      - ./chop{{.EXE_EXT}}
    vars:
      EXE_EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'

  build:
    desc: build only
    cmds:
      - task: fmt
      - go build ./cmd/chop/chop.go

  fmt:
    desc: go fmt
    cmds:
      - go fmt ./...

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  lint:
    desc: Runs golint
    cmds:
      - task: fmt
      - golint {{catLines .GO_PACKAGES}}

  test:
    desc: Runs test suite
    cmds:
      - task: fmt
      - go test {{catLines .GO_PACKAGES}}

  ci:
    desc: run CI things
    cmds:
      - task: lint
      - task: test

  packages:
    cmds:
      - echo '{{.GO_PACKAGES}}'
    silent: true
